DROP TABLE IF EXISTS "ods_anytxn_bm_acct_loan_detl_his";

create table public.ods_anytxn_bm_acct_loan_detl_his
(
   "his_start_time" int4 NOT NULL,
   "his_end_time" int4 NOT NULL,
	txa_number varchar(32) not null,
	txa_type varchar(2) not null,
	txa_status varchar(1) default NULL::character varying,
	txa_business_module varchar(2) default NULL::character varying,
	txn_type varchar(5) default NULL::character varying,
	txn_code varchar(5) default NULL::character varying,
	txn_system_date timestamp,
	txn_effective_date timestamp,
	txn_effective_amnt numeric(18,5),
	txn_organization_id varchar(4) default NULL::character varying,
	txn_effective_currency varchar(3) default NULL::character varying,
	txn_posting_date date,
	txn_posting_time timestamp,
	txn_posting_amnt numeric(18,5),
	txn_posting_currency varchar(3) default NULL::character varying,
	txn_settle_amnt numeric(18,5),
	txn_settle_currency varchar(3) default NULL::character varying,
	txn_markup_percent numeric(18,6),
	txn_exchange_rate numeric(18,9),
	txn_plastic_number varchar(19) default NULL::character varying,
	txn_card_number_post varchar(19) default NULL::character varying,
	txn_cust_number varchar(32) default NULL::character varying,
	txn_intr_start_date date,
	loan_payment_due_date date,
	txn_waive_intr_flag varchar(1) default NULL::character varying,
	txn_waive_latechg_flag varchar(1) default NULL::character varying,
	txn_chargeoff_flag varchar(1) default NULL::character varying,
	txn_chargeoff_amnt numeric(18,5),
	txn_chargeoff_date date,
	txn_chargeoff_rsn_cd varchar(4) default NULL::character varying,
	txn_orig_txa_number varchar(32) default NULL::character varying,
	loan_tenor integer,
	txn_create_date timestamp not null,
	txn_last_update_date timestamp,
	txn_last_update_operator varchar(40) default NULL::character varying,
	txn_parent_txa_number varchar(32) default NULL::character varying,
	txn_stmt_repayment_tableid varchar(6) default NULL::character varying,
	pro_cd varchar(6) default NULL::character varying,
	txn_orig_txa_type varchar(2) default NULL::character varying,
	txn_parent_txa_type varchar(2) default NULL::character varying,
	txn_pen_intr_table_id varchar(6) default NULL::character varying,
	txn_cs_pen_intr_table_id varchar(6) default NULL::character varying,
	txn_cs_intr_table_id varchar(6) default NULL::character varying,
	txn_cs_loan_fee_table_id varchar(6) default NULL::character varying,
	txn_cs_loan_prepay_table_id varchar(6) default NULL::character varying,
	txn_cs_loan_payoff_table_id varchar(6) default NULL::character varying,
	txn_intr_table_id varchar(6) default NULL::character varying,
	txn_connect_txa_number varchar(32) default NULL::character varying,
	txn_connect_txa_type varchar(2) default NULL::character varying,
	loan_banlance_type_flag varchar(2) default NULL::character varying,
	loan_tenor_typ varchar(4) default NULL::character varying,
	loan_acq_ref_nbr varchar(32) default NULL::character varying,
	loan_operator_id varchar(20) default NULL::character varying,
	loan_mechant_name varchar(60) default NULL::character varying,
	loan_b018_merchant_typ varchar(4) default NULL::character varying,
	loan_order_number varchar(32) default NULL::character varying,
	loan_billing_tenor integer,
	loan_order_seq varchar(3) default NULL::character varying,
	loan_next_loan_billing_cycle date,
	loan_charge_freq varchar(1) default NULL::character varying,
	business_type varchar(2) default NULL::character varying,
	product_code varchar(32) default NULL::character varying,
	compensatory_days integer,
	txn_late_charge_fee_table_id varchar(6) default NULL::character varying,
	txn_channel varchar(32) default NULL::character varying,
	txn_sub_channel_1 varchar(6) default NULL::character varying,
	txn_sub_channel_2 varchar(6) default NULL::character varying,
	fus_percentage numeric(3,2),
	fus_id varchar(4) default NULL::character varying,
	joint_loan_flag varchar(1) default NULL::character varying,
	hp_posting_amnt numeric(18,2),
	ot_posting_amnt numeric(18,2),
	txn_partner_pen_intr_table_id varchar(6) default NULL::character varying,
	create_time timestamp not null,
	last_update_time timestamp not null,
	real_channel varchar(23) not null,
	 CONSTRAINT ods_anytxn_bm_acct_loan_detl_his_pkey PRIMARY KEY (his_end_time,txa_number)

);


