DROP TABLE IF EXISTS "ods_anytxn_bm_intr_accu_acct_daily_snap";
CREATE TABLE "ods_anytxn_bm_intr_accu_acct_daily_snap" (
  "biz_date" int4 NOT NULL,
  "txa_number" varchar(2000) COLLATE "pg_catalog"."default" NOT NULL,
  "txn_orig_txa_number" varchar(2000) COLLATE "pg_catalog"."default",
  "txn_system_date" timestamp(6),
  "txa_status" varchar(100) COLLATE "pg_catalog"."default",
  "txa_type" varchar(100) COLLATE "pg_catalog"."default",
  "txa_business_module" varchar(100) COLLATE "pg_catalog"."default",
  "txn_effective_currency" varchar(100) COLLATE "pg_catalog"."default",
  "txn_create_date" timestamp(6),
  "txn_last_update_date" timestamp(6),
  "txn_last_update_operator" varchar(2000) COLLATE "pg_catalog"."default",
  "txn_cust_number" varchar(2000) COLLATE "pg_catalog"."default",
  "txn_organization_id" varchar(100) COLLATE "pg_catalog"."default",
  "txn_intr_start_date" date,
  "txn_plastic_number" varchar(2000) COLLATE "pg_catalog"."default",
  "txn_parent_txa_number" varchar(2000) COLLATE "pg_catalog"."default",
  "txn_stmt_repayment_tableid" varchar(2000) COLLATE "pg_catalog"."default",
  "pro_cd" varchar(2000) COLLATE "pg_catalog"."default",
  "product_code" varchar(2000) COLLATE "pg_catalog"."default",
  "txn_orig_txa_type" varchar(100) COLLATE "pg_catalog"."default",
  "txn_parent_txa_type" varchar(100) COLLATE "pg_catalog"."default",
  "txn_root_txa_type" varchar(100) COLLATE "pg_catalog"."default",
  "accu_intr_amnt" numeric,
  "accu_intr_flag" varchar(100) COLLATE "pg_catalog"."default",
  "accu_last_int_settle_date" date,
  "accu_total_accru_intr" numeric,
  "accu_total_accru_days" int4,
  "accu_new_accru_intr" numeric,
  "accu_new_accru_days" int4,
  "accu_new_accru_from_date" date,
  "accu_new_accru_to_date" date,
  "cs_accu_new_accru_from_date" date,
  "accu_stop_accru_flag" varchar(100) COLLATE "pg_catalog"."default",
  "accu_last_statment_date" date,
  "accu_curr_intr_table_id" varchar(100) COLLATE "pg_catalog"."default",
  "accu_root_txa_number" varchar(100) COLLATE "pg_catalog"."default",
  "accu_intr_currency" varchar(100) COLLATE "pg_catalog"."default",
  "accu_pymt_within_grace_flag" varchar(2000) COLLATE "pg_catalog"."default",
  "loan_order_seq" varchar(100) COLLATE "pg_catalog"."default",
  "loan_tenor_typ" varchar(2000) COLLATE "pg_catalog"."default",
  "loan_order_number" varchar(100) COLLATE "pg_catalog"."default",
  "loan_payment_due_date" date,
  "loan_billing_tenor" int4,
  "accu_curr_pen_intr_table_id" varchar(100) COLLATE "pg_catalog"."default",
  "cs_accu_total_accru_intr" numeric,
  "cs_accu_total_accru_days" int4,
  "cs_accu_new_accru_intr" numeric,
  "cs_accu_new_accru_days" int4,
  "cs_accu_stop_accru_flag" varchar(100) COLLATE "pg_catalog"."default",
  "cs_accu_curr_pen_intr_table_id" varchar(100) COLLATE "pg_catalog"."default",
  "cs_accu_curr_intr_table_id" varchar(100) COLLATE "pg_catalog"."default",
  "hava_charge_up" int4,
  "compensatory_flag" varchar(100) COLLATE "pg_catalog"."default",
  "bal_trans_flag" varchar(100) COLLATE "pg_catalog"."default",
  "loan_daily_rate" numeric,
  "max_interest_amnt" numeric,
  "fus_id" varchar(2000) COLLATE "pg_catalog"."default",
  "joint_loan_flag" varchar(100) COLLATE "pg_catalog"."default",
  "txn_channel" varchar(2000) COLLATE "pg_catalog"."default",
  "last_update_time" timestamp(6),
  "cs_accu_daily_adjustment" numeric,
  "accu_daily_adjustment" numeric,
  "accu_daily_after_adjustment" numeric,
  "cs_accu_daily_after_adjustment" numeric,
  "accu_daily_provision" numeric,
  "cs_accu_daily_provision" numeric,
  "create_time" timestamp(6),
  "real_channel" varchar(2000) COLLATE "pg_catalog"."default",
  CONSTRAINT "ods_anytxn_bm_intr_accu_acct_daily_snap_pkey" PRIMARY KEY ("biz_date", "txa_number")
);